# Generated by Django 3.0.4 on 2021-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200314_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
